name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MISE_GO_SET_GOROOT: false
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - run: mise r lint
      - run: mise r test
